//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ClientesExternos.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ClientextEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ClientextEntities usando la cadena de conexión encontrada en la sección 'ClientextEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClientextEntities() : base("name=ClientextEntities", "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClientextEntities.
        /// </summary>
        public ClientextEntities(string connectionString) : base(connectionString, "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClientextEntities.
        /// </summary>
        public ClientextEntities(EntityConnection connection) : base(connection, "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos> articulos
        {
            get
            {
                if ((_articulos == null))
                {
                    _articulos = base.CreateObjectSet<articulos>("articulos");
                }
                return _articulos;
            }
        }
        private ObjectSet<articulos> _articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clientes> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<clientes>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<clientes> _clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tarimas_entradas> tarimas_entradas
        {
            get
            {
                if ((_tarimas_entradas == null))
                {
                    _tarimas_entradas = base.CreateObjectSet<tarimas_entradas>("tarimas_entradas");
                }
                return _tarimas_entradas;
            }
        }
        private ObjectSet<tarimas_entradas> _tarimas_entradas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tarimas_salidas> tarimas_salidas
        {
            get
            {
                if ((_tarimas_salidas == null))
                {
                    _tarimas_salidas = base.CreateObjectSet<tarimas_salidas>("tarimas_salidas");
                }
                return _tarimas_salidas;
            }
        }
        private ObjectSet<tarimas_salidas> _tarimas_salidas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos(articulos articulos)
        {
            base.AddObject("articulos", articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclientes(clientes clientes)
        {
            base.AddObject("clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tarimas_entradas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotarimas_entradas(tarimas_entradas tarimas_entradas)
        {
            base.AddObject("tarimas_entradas", tarimas_entradas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tarimas_salidas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotarimas_salidas(tarimas_salidas tarimas_salidas)
        {
            base.AddObject("tarimas_salidas", tarimas_salidas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="id_usuario_creador">Valor inicial de la propiedad id_usuario_creador.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static articulos Createarticulos(global::System.String codigo, global::System.String nombre, global::System.Int64 id_cliente, global::System.Int64 id_usuario_creador, global::System.DateTime fecha_creacion, global::System.String estatus)
        {
            articulos articulos = new articulos();
            articulos.codigo = codigo;
            articulos.nombre = nombre;
            articulos.id_cliente = id_cliente;
            articulos.id_usuario_creador = id_usuario_creador;
            articulos.fecha_creacion = fecha_creacion;
            articulos.estatus = estatus;
            return articulos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                if (_nombre != value)
                {
                    OnnombreChanging(value);
                    ReportPropertyChanging("nombre");
                    _nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombre");
                    OnnombreChanged();
                }
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario_creador
        {
            get
            {
                return _id_usuario_creador;
            }
            set
            {
                Onid_usuario_creadorChanging(value);
                ReportPropertyChanging("id_usuario_creador");
                _id_usuario_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_creador");
                Onid_usuario_creadorChanged();
            }
        }
        private global::System.Int64 _id_usuario_creador;
        partial void Onid_usuario_creadorChanging(global::System.Int64 value);
        partial void Onid_usuario_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_usuario_ultima_modificacion
        {
            get
            {
                return _id_usuario_ultima_modificacion;
            }
            set
            {
                Onid_usuario_ultima_modificacionChanging(value);
                ReportPropertyChanging("id_usuario_ultima_modificacion");
                _id_usuario_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_ultima_modificacion");
                Onid_usuario_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.Int64> _id_usuario_ultima_modificacion;
        partial void Onid_usuario_ultima_modificacionChanging(Nullable<global::System.Int64> value);
        partial void Onid_usuario_ultima_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ultima_modificacion
        {
            get
            {
                return _fecha_ultima_modificacion;
            }
            set
            {
                Onfecha_ultima_modificacionChanging(value);
                ReportPropertyChanging("fecha_ultima_modificacion");
                _fecha_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ultima_modificacion");
                Onfecha_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ultima_modificacion;
        partial void Onfecha_ultima_modificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ultima_modificacionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clientes.
        /// </summary>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="serie">Valor inicial de la propiedad serie.</param>
        /// <param name="id_usuario_creador">Valor inicial de la propiedad id_usuario_creador.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static clientes Createclientes(global::System.Int64 id_cliente, global::System.String nombre, global::System.String serie, global::System.Int32 id_usuario_creador, global::System.DateTime fecha_creacion, global::System.String estatus)
        {
            clientes clientes = new clientes();
            clientes.id_cliente = id_cliente;
            clientes.nombre = nombre;
            clientes.serie = serie;
            clientes.id_usuario_creador = id_usuario_creador;
            clientes.fecha_creacion = fecha_creacion;
            clientes.estatus = estatus;
            return clientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serie
        {
            get
            {
                return _serie;
            }
            set
            {
                OnserieChanging(value);
                ReportPropertyChanging("serie");
                _serie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("serie");
                OnserieChanged();
            }
        }
        private global::System.String _serie;
        partial void OnserieChanging(global::System.String value);
        partial void OnserieChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario_creador
        {
            get
            {
                return _id_usuario_creador;
            }
            set
            {
                Onid_usuario_creadorChanging(value);
                ReportPropertyChanging("id_usuario_creador");
                _id_usuario_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_creador");
                Onid_usuario_creadorChanged();
            }
        }
        private global::System.Int32 _id_usuario_creador;
        partial void Onid_usuario_creadorChanging(global::System.Int32 value);
        partial void Onid_usuario_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_usuario_ultima_modificacion
        {
            get
            {
                return _id_usuario_ultima_modificacion;
            }
            set
            {
                Onid_usuario_ultima_modificacionChanging(value);
                ReportPropertyChanging("id_usuario_ultima_modificacion");
                _id_usuario_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_ultima_modificacion");
                Onid_usuario_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_usuario_ultima_modificacion;
        partial void Onid_usuario_ultima_modificacionChanging(Nullable<global::System.Int32> value);
        partial void Onid_usuario_ultima_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ultima_modificacion
        {
            get
            {
                return _fecha_ultima_modificacion;
            }
            set
            {
                Onfecha_ultima_modificacionChanging(value);
                ReportPropertyChanging("fecha_ultima_modificacion");
                _fecha_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ultima_modificacion");
                Onfecha_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ultima_modificacion;
        partial void Onfecha_ultima_modificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ultima_modificacionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="tarimas_entradas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tarimas_entradas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tarimas_entradas.
        /// </summary>
        /// <param name="id_tarima">Valor inicial de la propiedad id_tarima.</param>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="codigo_articulo">Valor inicial de la propiedad codigo_articulo.</param>
        /// <param name="num_cajas">Valor inicial de la propiedad num_cajas.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="fecha_ingreso">Valor inicial de la propiedad fecha_ingreso.</param>
        public static tarimas_entradas Createtarimas_entradas(global::System.Int64 id_tarima, global::System.Int64 id_cliente, global::System.String codigo_articulo, global::System.Int32 num_cajas, global::System.Decimal peso, global::System.DateTime fecha_ingreso)
        {
            tarimas_entradas tarimas_entradas = new tarimas_entradas();
            tarimas_entradas.id_tarima = id_tarima;
            tarimas_entradas.id_cliente = id_cliente;
            tarimas_entradas.codigo_articulo = codigo_articulo;
            tarimas_entradas.num_cajas = num_cajas;
            tarimas_entradas.peso = peso;
            tarimas_entradas.fecha_ingreso = fecha_ingreso;
            return tarimas_entradas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_tarima
        {
            get
            {
                return _id_tarima;
            }
            set
            {
                if (_id_tarima != value)
                {
                    Onid_tarimaChanging(value);
                    ReportPropertyChanging("id_tarima");
                    _id_tarima = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tarima");
                    Onid_tarimaChanged();
                }
            }
        }
        private global::System.Int64 _id_tarima;
        partial void Onid_tarimaChanging(global::System.Int64 value);
        partial void Onid_tarimaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_articulo
        {
            get
            {
                return _codigo_articulo;
            }
            set
            {
                Oncodigo_articuloChanging(value);
                ReportPropertyChanging("codigo_articulo");
                _codigo_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo_articulo");
                Oncodigo_articuloChanged();
            }
        }
        private global::System.String _codigo_articulo;
        partial void Oncodigo_articuloChanging(global::System.String value);
        partial void Oncodigo_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_cajas
        {
            get
            {
                return _num_cajas;
            }
            set
            {
                Onnum_cajasChanging(value);
                ReportPropertyChanging("num_cajas");
                _num_cajas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_cajas");
                Onnum_cajasChanged();
            }
        }
        private global::System.Int32 _num_cajas;
        partial void Onnum_cajasChanging(global::System.Int32 value);
        partial void Onnum_cajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private global::System.Decimal _peso;
        partial void OnpesoChanging(global::System.Decimal value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_ingreso
        {
            get
            {
                return _fecha_ingreso;
            }
            set
            {
                Onfecha_ingresoChanging(value);
                ReportPropertyChanging("fecha_ingreso");
                _fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ingreso");
                Onfecha_ingresoChanged();
            }
        }
        private global::System.DateTime _fecha_ingreso;
        partial void Onfecha_ingresoChanging(global::System.DateTime value);
        partial void Onfecha_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="tarimas_salidas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tarimas_salidas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tarimas_salidas.
        /// </summary>
        /// <param name="id_tarima">Valor inicial de la propiedad id_tarima.</param>
        /// <param name="codigo_articulo">Valor inicial de la propiedad codigo_articulo.</param>
        /// <param name="num_cajas">Valor inicial de la propiedad num_cajas.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="fecha_salida">Valor inicial de la propiedad fecha_salida.</param>
        public static tarimas_salidas Createtarimas_salidas(global::System.Int64 id_tarima, global::System.String codigo_articulo, global::System.Int32 num_cajas, global::System.Decimal peso, global::System.DateTime fecha_salida)
        {
            tarimas_salidas tarimas_salidas = new tarimas_salidas();
            tarimas_salidas.id_tarima = id_tarima;
            tarimas_salidas.codigo_articulo = codigo_articulo;
            tarimas_salidas.num_cajas = num_cajas;
            tarimas_salidas.peso = peso;
            tarimas_salidas.fecha_salida = fecha_salida;
            return tarimas_salidas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_tarima
        {
            get
            {
                return _id_tarima;
            }
            set
            {
                if (_id_tarima != value)
                {
                    Onid_tarimaChanging(value);
                    ReportPropertyChanging("id_tarima");
                    _id_tarima = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tarima");
                    Onid_tarimaChanged();
                }
            }
        }
        private global::System.Int64 _id_tarima;
        partial void Onid_tarimaChanging(global::System.Int64 value);
        partial void Onid_tarimaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_articulo
        {
            get
            {
                return _codigo_articulo;
            }
            set
            {
                Oncodigo_articuloChanging(value);
                ReportPropertyChanging("codigo_articulo");
                _codigo_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo_articulo");
                Oncodigo_articuloChanged();
            }
        }
        private global::System.String _codigo_articulo;
        partial void Oncodigo_articuloChanging(global::System.String value);
        partial void Oncodigo_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_cajas
        {
            get
            {
                return _num_cajas;
            }
            set
            {
                Onnum_cajasChanging(value);
                ReportPropertyChanging("num_cajas");
                _num_cajas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_cajas");
                Onnum_cajasChanged();
            }
        }
        private global::System.Int32 _num_cajas;
        partial void Onnum_cajasChanging(global::System.Int32 value);
        partial void Onnum_cajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private global::System.Decimal _peso;
        partial void OnpesoChanging(global::System.Decimal value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_salida
        {
            get
            {
                return _fecha_salida;
            }
            set
            {
                Onfecha_salidaChanging(value);
                ReportPropertyChanging("fecha_salida");
                _fecha_salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_salida");
                Onfecha_salidaChanged();
            }
        }
        private global::System.DateTime _fecha_salida;
        partial void Onfecha_salidaChanging(global::System.DateTime value);
        partial void Onfecha_salidaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="nombre_completo">Valor inicial de la propiedad nombre_completo.</param>
        /// <param name="nombre_usuario">Valor inicial de la propiedad nombre_usuario.</param>
        /// <param name="contrasenia">Valor inicial de la propiedad contrasenia.</param>
        /// <param name="permisos">Valor inicial de la propiedad permisos.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static usuarios Createusuarios(global::System.Int64 id_usuario, global::System.String nombre_completo, global::System.String nombre_usuario, global::System.String contrasenia, global::System.String permisos, global::System.String estatus)
        {
            usuarios usuarios = new usuarios();
            usuarios.id_usuario = id_usuario;
            usuarios.nombre_completo = nombre_completo;
            usuarios.nombre_usuario = nombre_usuario;
            usuarios.contrasenia = contrasenia;
            usuarios.permisos = permisos;
            usuarios.estatus = estatus;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_completo
        {
            get
            {
                return _nombre_completo;
            }
            set
            {
                Onnombre_completoChanging(value);
                ReportPropertyChanging("nombre_completo");
                _nombre_completo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_completo");
                Onnombre_completoChanged();
            }
        }
        private global::System.String _nombre_completo;
        partial void Onnombre_completoChanging(global::System.String value);
        partial void Onnombre_completoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenia
        {
            get
            {
                return _contrasenia;
            }
            set
            {
                OncontraseniaChanging(value);
                ReportPropertyChanging("contrasenia");
                _contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenia");
                OncontraseniaChanged();
            }
        }
        private global::System.String _contrasenia;
        partial void OncontraseniaChanging(global::System.String value);
        partial void OncontraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String permisos
        {
            get
            {
                return _permisos;
            }
            set
            {
                OnpermisosChanging(value);
                ReportPropertyChanging("permisos");
                _permisos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("permisos");
                OnpermisosChanged();
            }
        }
        private global::System.String _permisos;
        partial void OnpermisosChanging(global::System.String value);
        partial void OnpermisosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }

    #endregion

    
}
