//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ClientextModel", "fk_articulo", "articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.articulos), "tarimas_entradas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_entradas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario1", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.usuarios), "articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.articulos), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario2", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ClientesExternos.Entity.usuarios), "articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.articulos), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_cliente", "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.clientes), "tarimas_entradas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_entradas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario1c", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.usuarios), "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.clientes), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario2c", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ClientesExternos.Entity.usuarios), "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.clientes), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.usuarios), "tarimas_entradas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_entradas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_articulo_s", "articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.articulos), "tarimas_salidas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_salidas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_cliente_s", "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.clientes), "tarimas_salidas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_salidas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_tarima_s", "tarimas_entradas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.tarimas_entradas), "tarimas_salidas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_salidas), true)]
[assembly: EdmRelationshipAttribute("ClientextModel", "fk_usuario_s", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientesExternos.Entity.usuarios), "tarimas_salidas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientesExternos.Entity.tarimas_salidas), true)]

#endregion

namespace ClientesExternos.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ClientextEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ClientextEntities usando la cadena de conexión encontrada en la sección 'ClientextEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClientextEntities() : base("name=ClientextEntities", "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClientextEntities.
        /// </summary>
        public ClientextEntities(string connectionString) : base(connectionString, "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClientextEntities.
        /// </summary>
        public ClientextEntities(EntityConnection connection) : base(connection, "ClientextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos> articulos
        {
            get
            {
                if ((_articulos == null))
                {
                    _articulos = base.CreateObjectSet<articulos>("articulos");
                }
                return _articulos;
            }
        }
        private ObjectSet<articulos> _articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clientes> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<clientes>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<clientes> _clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tarimas_entradas> tarimas_entradas
        {
            get
            {
                if ((_tarimas_entradas == null))
                {
                    _tarimas_entradas = base.CreateObjectSet<tarimas_entradas>("tarimas_entradas");
                }
                return _tarimas_entradas;
            }
        }
        private ObjectSet<tarimas_entradas> _tarimas_entradas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tarimas_salidas> tarimas_salidas
        {
            get
            {
                if ((_tarimas_salidas == null))
                {
                    _tarimas_salidas = base.CreateObjectSet<tarimas_salidas>("tarimas_salidas");
                }
                return _tarimas_salidas;
            }
        }
        private ObjectSet<tarimas_salidas> _tarimas_salidas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vw_inventario> vw_inventario
        {
            get
            {
                if ((_vw_inventario == null))
                {
                    _vw_inventario = base.CreateObjectSet<vw_inventario>("vw_inventario");
                }
                return _vw_inventario;
            }
        }
        private ObjectSet<vw_inventario> _vw_inventario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<plantillas_etiquetas> plantillas_etiquetas
        {
            get
            {
                if ((_plantillas_etiquetas == null))
                {
                    _plantillas_etiquetas = base.CreateObjectSet<plantillas_etiquetas>("plantillas_etiquetas");
                }
                return _plantillas_etiquetas;
            }
        }
        private ObjectSet<plantillas_etiquetas> _plantillas_etiquetas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos(articulos articulos)
        {
            base.AddObject("articulos", articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclientes(clientes clientes)
        {
            base.AddObject("clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tarimas_entradas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotarimas_entradas(tarimas_entradas tarimas_entradas)
        {
            base.AddObject("tarimas_entradas", tarimas_entradas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tarimas_salidas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotarimas_salidas(tarimas_salidas tarimas_salidas)
        {
            base.AddObject("tarimas_salidas", tarimas_salidas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vw_inventario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovw_inventario(vw_inventario vw_inventario)
        {
            base.AddObject("vw_inventario", vw_inventario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet plantillas_etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToplantillas_etiquetas(plantillas_etiquetas plantillas_etiquetas)
        {
            base.AddObject("plantillas_etiquetas", plantillas_etiquetas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos.
        /// </summary>
        /// <param name="id_articulo">Valor inicial de la propiedad id_articulo.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="id_usuario_creador">Valor inicial de la propiedad id_usuario_creador.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static articulos Createarticulos(global::System.Int64 id_articulo, global::System.String codigo, global::System.String nombre, global::System.Int64 id_cliente, global::System.Int64 id_usuario_creador, global::System.DateTime fecha_creacion, global::System.String estatus)
        {
            articulos articulos = new articulos();
            articulos.id_articulo = id_articulo;
            articulos.codigo = codigo;
            articulos.nombre = nombre;
            articulos.id_cliente = id_cliente;
            articulos.id_usuario_creador = id_usuario_creador;
            articulos.fecha_creacion = fecha_creacion;
            articulos.estatus = estatus;
            return articulos;
        }

        #endregion

        #region Propiedades primitivas

        public global::System.String codigo_nombre
        {
            get
            {
                return _codigo + " - " + _nombre;
            }
        }

        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_articulo
        {
            get
            {
                return _id_articulo;
            }
            set
            {
                if (_id_articulo != value)
                {
                    Onid_articuloChanging(value);
                    ReportPropertyChanging("id_articulo");
                    _id_articulo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_articulo");
                    Onid_articuloChanged();
                }
            }
        }
        private global::System.Int64 _id_articulo;
        partial void Onid_articuloChanging(global::System.Int64 value);
        partial void Onid_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario_creador
        {
            get
            {
                return _id_usuario_creador;
            }
            set
            {
                Onid_usuario_creadorChanging(value);
                ReportPropertyChanging("id_usuario_creador");
                _id_usuario_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_creador");
                Onid_usuario_creadorChanged();
            }
        }
        private global::System.Int64 _id_usuario_creador;
        partial void Onid_usuario_creadorChanging(global::System.Int64 value);
        partial void Onid_usuario_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_usuario_ultima_modificacion
        {
            get
            {
                return _id_usuario_ultima_modificacion;
            }
            set
            {
                Onid_usuario_ultima_modificacionChanging(value);
                ReportPropertyChanging("id_usuario_ultima_modificacion");
                _id_usuario_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_ultima_modificacion");
                Onid_usuario_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.Int64> _id_usuario_ultima_modificacion;
        partial void Onid_usuario_ultima_modificacionChanging(Nullable<global::System.Int64> value);
        partial void Onid_usuario_ultima_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ultima_modificacion
        {
            get
            {
                return _fecha_ultima_modificacion;
            }
            set
            {
                Onfecha_ultima_modificacionChanging(value);
                ReportPropertyChanging("fecha_ultima_modificacion");
                _fecha_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ultima_modificacion");
                Onfecha_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ultima_modificacion;
        partial void Onfecha_ultima_modificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ultima_modificacionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_articulo", "tarimas_entradas")]
        public EntityCollection<tarimas_entradas> tarimas_entradas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_entradas>("ClientextModel.fk_articulo", "tarimas_entradas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_entradas>("ClientextModel.fk_articulo", "tarimas_entradas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario1", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario1", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario2", "usuarios")]
        public usuarios usuarios1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuarios1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario2", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_articulo_s", "tarimas_salidas")]
        public EntityCollection<tarimas_salidas> tarimas_salidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_salidas>("ClientextModel.fk_articulo_s", "tarimas_salidas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_salidas>("ClientextModel.fk_articulo_s", "tarimas_salidas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clientes.
        /// </summary>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="serie">Valor inicial de la propiedad serie.</param>
        /// <param name="id_usuario_creador">Valor inicial de la propiedad id_usuario_creador.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static clientes Createclientes(global::System.Int64 id_cliente, global::System.String nombre, global::System.String serie, global::System.Int64 id_usuario_creador, global::System.DateTime fecha_creacion, global::System.String estatus)
        {
            clientes clientes = new clientes();
            clientes.id_cliente = id_cliente;
            clientes.nombre = nombre;
            clientes.serie = serie;
            clientes.id_usuario_creador = id_usuario_creador;
            clientes.fecha_creacion = fecha_creacion;
            clientes.estatus = estatus;
            return clientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serie
        {
            get
            {
                return _serie;
            }
            set
            {
                OnserieChanging(value);
                ReportPropertyChanging("serie");
                _serie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("serie");
                OnserieChanged();
            }
        }
        private global::System.String _serie;
        partial void OnserieChanging(global::System.String value);
        partial void OnserieChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario_creador
        {
            get
            {
                return _id_usuario_creador;
            }
            set
            {
                Onid_usuario_creadorChanging(value);
                ReportPropertyChanging("id_usuario_creador");
                _id_usuario_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_creador");
                Onid_usuario_creadorChanged();
            }
        }
        private global::System.Int64 _id_usuario_creador;
        partial void Onid_usuario_creadorChanging(global::System.Int64 value);
        partial void Onid_usuario_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_usuario_ultima_modificacion
        {
            get
            {
                return _id_usuario_ultima_modificacion;
            }
            set
            {
                Onid_usuario_ultima_modificacionChanging(value);
                ReportPropertyChanging("id_usuario_ultima_modificacion");
                _id_usuario_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_ultima_modificacion");
                Onid_usuario_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.Int64> _id_usuario_ultima_modificacion;
        partial void Onid_usuario_ultima_modificacionChanging(Nullable<global::System.Int64> value);
        partial void Onid_usuario_ultima_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ultima_modificacion
        {
            get
            {
                return _fecha_ultima_modificacion;
            }
            set
            {
                Onfecha_ultima_modificacionChanging(value);
                ReportPropertyChanging("fecha_ultima_modificacion");
                _fecha_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ultima_modificacion");
                Onfecha_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ultima_modificacion;
        partial void Onfecha_ultima_modificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ultima_modificacionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_cliente", "tarimas_entradas")]
        public EntityCollection<tarimas_entradas> tarimas_entradas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_entradas>("ClientextModel.fk_cliente", "tarimas_entradas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_entradas>("ClientextModel.fk_cliente", "tarimas_entradas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario1c", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1c", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1c", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario1c", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario1c", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario2c", "usuarios")]
        public usuarios usuarios1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2c", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2c", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuarios1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario2c", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario2c", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_cliente_s", "tarimas_salidas")]
        public EntityCollection<tarimas_salidas> tarimas_salidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_salidas>("ClientextModel.fk_cliente_s", "tarimas_salidas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_salidas>("ClientextModel.fk_cliente_s", "tarimas_salidas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="plantillas_etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class plantillas_etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto plantillas_etiquetas.
        /// </summary>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="comando">Valor inicial de la propiedad comando.</param>
        public static plantillas_etiquetas Createplantillas_etiquetas(global::System.Int64 id_etiqueta, global::System.String nombre, global::System.String comando)
        {
            plantillas_etiquetas plantillas_etiquetas = new plantillas_etiquetas();
            plantillas_etiquetas.id_etiqueta = id_etiqueta;
            plantillas_etiquetas.nombre = nombre;
            plantillas_etiquetas.comando = comando;
            return plantillas_etiquetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                if (_id_etiqueta != value)
                {
                    Onid_etiquetaChanging(value);
                    ReportPropertyChanging("id_etiqueta");
                    _id_etiqueta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_etiqueta");
                    Onid_etiquetaChanged();
                }
            }
        }
        private global::System.Int64 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int64 value);
        partial void Onid_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comando
        {
            get
            {
                return _comando;
            }
            set
            {
                OncomandoChanging(value);
                ReportPropertyChanging("comando");
                _comando = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comando");
                OncomandoChanged();
            }
        }
        private global::System.String _comando;
        partial void OncomandoChanging(global::System.String value);
        partial void OncomandoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] imagen
        {
            get
            {
                return StructuralObject.GetValidValue(_imagen);
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.Byte[] _imagen;
        partial void OnimagenChanging(global::System.Byte[] value);
        partial void OnimagenChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="tarimas_entradas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tarimas_entradas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tarimas_entradas.
        /// </summary>
        /// <param name="id_tarima">Valor inicial de la propiedad id_tarima.</param>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="id_articulo">Valor inicial de la propiedad id_articulo.</param>
        /// <param name="num_cajas">Valor inicial de la propiedad num_cajas.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="fecha_ingreso">Valor inicial de la propiedad fecha_ingreso.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        public static tarimas_entradas Createtarimas_entradas(global::System.Int64 id_tarima, global::System.Int64 id_cliente, global::System.Int64 id_articulo, global::System.Int32 num_cajas, global::System.Decimal peso, global::System.DateTime fecha_ingreso, global::System.Int64 id_usuario)
        {
            tarimas_entradas tarimas_entradas = new tarimas_entradas();
            tarimas_entradas.id_tarima = id_tarima;
            tarimas_entradas.id_cliente = id_cliente;
            tarimas_entradas.id_articulo = id_articulo;
            tarimas_entradas.num_cajas = num_cajas;
            tarimas_entradas.peso = peso;
            tarimas_entradas.fecha_ingreso = fecha_ingreso;
            tarimas_entradas.id_usuario = id_usuario;
            return tarimas_entradas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_tarima
        {
            get
            {
                return _id_tarima;
            }
            set
            {
                if (_id_tarima != value)
                {
                    Onid_tarimaChanging(value);
                    ReportPropertyChanging("id_tarima");
                    _id_tarima = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tarima");
                    Onid_tarimaChanged();
                }
            }
        }
        private global::System.Int64 _id_tarima;
        partial void Onid_tarimaChanging(global::System.Int64 value);
        partial void Onid_tarimaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_articulo
        {
            get
            {
                return _id_articulo;
            }
            set
            {
                Onid_articuloChanging(value);
                ReportPropertyChanging("id_articulo");
                _id_articulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_articulo");
                Onid_articuloChanged();
            }
        }
        private global::System.Int64 _id_articulo;
        partial void Onid_articuloChanging(global::System.Int64 value);
        partial void Onid_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_cajas
        {
            get
            {
                return _num_cajas;
            }
            set
            {
                Onnum_cajasChanging(value);
                ReportPropertyChanging("num_cajas");
                _num_cajas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_cajas");
                Onnum_cajasChanged();
            }
        }
        private global::System.Int32 _num_cajas;
        partial void Onnum_cajasChanging(global::System.Int32 value);
        partial void Onnum_cajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private global::System.Decimal _peso;
        partial void OnpesoChanging(global::System.Decimal value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_ingreso
        {
            get
            {
                return _fecha_ingreso;
            }
            set
            {
                Onfecha_ingresoChanging(value);
                ReportPropertyChanging("fecha_ingreso");
                _fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ingreso");
                Onfecha_ingresoChanged();
            }
        }
        private global::System.DateTime _fecha_ingreso;
        partial void Onfecha_ingresoChanging(global::System.DateTime value);
        partial void Onfecha_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_tarima_cliente
        {
            get
            {
                return _numero_tarima_cliente;
            }
            set
            {
                Onnumero_tarima_clienteChanging(value);
                ReportPropertyChanging("numero_tarima_cliente");
                _numero_tarima_cliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_tarima_cliente");
                Onnumero_tarima_clienteChanged();
            }
        }
        private global::System.String _numero_tarima_cliente;
        partial void Onnumero_tarima_clienteChanging(global::System.String value);
        partial void Onnumero_tarima_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_articulo", "articulos")]
        public articulos articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo", "articulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo", "articulos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<articulos> articulosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo", "articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<articulos>("ClientextModel.fk_articulo", "articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_cliente", "clientes")]
        public clientes clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente", "clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente", "clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clientes> clientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clientes>("ClientextModel.fk_cliente", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_tarima_s", "tarimas_salidas")]
        public EntityCollection<tarimas_salidas> tarimas_salidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_salidas>("ClientextModel.fk_tarima_s", "tarimas_salidas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_salidas>("ClientextModel.fk_tarima_s", "tarimas_salidas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="tarimas_salidas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tarimas_salidas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tarimas_salidas.
        /// </summary>
        /// <param name="id_maniobra">Valor inicial de la propiedad id_maniobra.</param>
        /// <param name="id_tarima">Valor inicial de la propiedad id_tarima.</param>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="id_articulo">Valor inicial de la propiedad id_articulo.</param>
        /// <param name="num_cajas">Valor inicial de la propiedad num_cajas.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="fecha_salida">Valor inicial de la propiedad fecha_salida.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        public static tarimas_salidas Createtarimas_salidas(global::System.Int64 id_maniobra, global::System.Int64 id_tarima, global::System.Int64 id_cliente, global::System.Int64 id_articulo, global::System.Int32 num_cajas, global::System.Decimal peso, global::System.DateTime fecha_salida, global::System.Int64 id_usuario)
        {
            tarimas_salidas tarimas_salidas = new tarimas_salidas();
            tarimas_salidas.id_maniobra = id_maniobra;
            tarimas_salidas.id_tarima = id_tarima;
            tarimas_salidas.id_cliente = id_cliente;
            tarimas_salidas.id_articulo = id_articulo;
            tarimas_salidas.num_cajas = num_cajas;
            tarimas_salidas.peso = peso;
            tarimas_salidas.fecha_salida = fecha_salida;
            tarimas_salidas.id_usuario = id_usuario;
            return tarimas_salidas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_maniobra
        {
            get
            {
                return _id_maniobra;
            }
            set
            {
                if (_id_maniobra != value)
                {
                    Onid_maniobraChanging(value);
                    ReportPropertyChanging("id_maniobra");
                    _id_maniobra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_maniobra");
                    Onid_maniobraChanged();
                }
            }
        }
        private global::System.Int64 _id_maniobra;
        partial void Onid_maniobraChanging(global::System.Int64 value);
        partial void Onid_maniobraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_tarima
        {
            get
            {
                return _id_tarima;
            }
            set
            {
                Onid_tarimaChanging(value);
                ReportPropertyChanging("id_tarima");
                _id_tarima = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_tarima");
                Onid_tarimaChanged();
            }
        }
        private global::System.Int64 _id_tarima;
        partial void Onid_tarimaChanging(global::System.Int64 value);
        partial void Onid_tarimaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_articulo
        {
            get
            {
                return _id_articulo;
            }
            set
            {
                Onid_articuloChanging(value);
                ReportPropertyChanging("id_articulo");
                _id_articulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_articulo");
                Onid_articuloChanged();
            }
        }
        private global::System.Int64 _id_articulo;
        partial void Onid_articuloChanging(global::System.Int64 value);
        partial void Onid_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 num_cajas
        {
            get
            {
                return _num_cajas;
            }
            set
            {
                Onnum_cajasChanging(value);
                ReportPropertyChanging("num_cajas");
                _num_cajas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_cajas");
                Onnum_cajasChanged();
            }
        }
        private global::System.Int32 _num_cajas;
        partial void Onnum_cajasChanging(global::System.Int32 value);
        partial void Onnum_cajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private global::System.Decimal _peso;
        partial void OnpesoChanging(global::System.Decimal value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_salida
        {
            get
            {
                return _fecha_salida;
            }
            set
            {
                Onfecha_salidaChanging(value);
                ReportPropertyChanging("fecha_salida");
                _fecha_salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_salida");
                Onfecha_salidaChanged();
            }
        }
        private global::System.DateTime _fecha_salida;
        partial void Onfecha_salidaChanging(global::System.DateTime value);
        partial void Onfecha_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_articulo_s", "articulos")]
        public articulos articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo_s", "articulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo_s", "articulos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<articulos> articulosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("ClientextModel.fk_articulo_s", "articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<articulos>("ClientextModel.fk_articulo_s", "articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_cliente_s", "clientes")]
        public clientes clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente_s", "clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente_s", "clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clientes> clientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("ClientextModel.fk_cliente_s", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clientes>("ClientextModel.fk_cliente_s", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_tarima_s", "tarimas_entradas")]
        public tarimas_entradas tarimas_entradas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tarimas_entradas>("ClientextModel.fk_tarima_s", "tarimas_entradas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tarimas_entradas>("ClientextModel.fk_tarima_s", "tarimas_entradas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tarimas_entradas> tarimas_entradasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tarimas_entradas>("ClientextModel.fk_tarima_s", "tarimas_entradas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tarimas_entradas>("ClientextModel.fk_tarima_s", "tarimas_entradas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario_s", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario_s", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario_s", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("ClientextModel.fk_usuario_s", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("ClientextModel.fk_usuario_s", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="nombre_completo">Valor inicial de la propiedad nombre_completo.</param>
        /// <param name="nombre_usuario">Valor inicial de la propiedad nombre_usuario.</param>
        /// <param name="contrasenia">Valor inicial de la propiedad contrasenia.</param>
        /// <param name="permisos">Valor inicial de la propiedad permisos.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static usuarios Createusuarios(global::System.Int64 id_usuario, global::System.String nombre_completo, global::System.String nombre_usuario, global::System.String contrasenia, global::System.String permisos, global::System.String estatus)
        {
            usuarios usuarios = new usuarios();
            usuarios.id_usuario = id_usuario;
            usuarios.nombre_completo = nombre_completo;
            usuarios.nombre_usuario = nombre_usuario;
            usuarios.contrasenia = contrasenia;
            usuarios.permisos = permisos;
            usuarios.estatus = estatus;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_completo
        {
            get
            {
                return _nombre_completo;
            }
            set
            {
                Onnombre_completoChanging(value);
                ReportPropertyChanging("nombre_completo");
                _nombre_completo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_completo");
                Onnombre_completoChanged();
            }
        }
        private global::System.String _nombre_completo;
        partial void Onnombre_completoChanging(global::System.String value);
        partial void Onnombre_completoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenia
        {
            get
            {
                return _contrasenia;
            }
            set
            {
                OncontraseniaChanging(value);
                ReportPropertyChanging("contrasenia");
                _contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenia");
                OncontraseniaChanged();
            }
        }
        private global::System.String _contrasenia;
        partial void OncontraseniaChanging(global::System.String value);
        partial void OncontraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String permisos
        {
            get
            {
                return _permisos;
            }
            set
            {
                OnpermisosChanging(value);
                ReportPropertyChanging("permisos");
                _permisos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("permisos");
                OnpermisosChanged();
            }
        }
        private global::System.String _permisos;
        partial void OnpermisosChanging(global::System.String value);
        partial void OnpermisosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario1", "articulos")]
        public EntityCollection<articulos> articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<articulos>("ClientextModel.fk_usuario1", "articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<articulos>("ClientextModel.fk_usuario1", "articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario2", "articulos")]
        public EntityCollection<articulos> articulos1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<articulos>("ClientextModel.fk_usuario2", "articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<articulos>("ClientextModel.fk_usuario2", "articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario1c", "clientes")]
        public EntityCollection<clientes> clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<clientes>("ClientextModel.fk_usuario1c", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<clientes>("ClientextModel.fk_usuario1c", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario2c", "clientes")]
        public EntityCollection<clientes> clientes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<clientes>("ClientextModel.fk_usuario2c", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<clientes>("ClientextModel.fk_usuario2c", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario", "tarimas_entradas")]
        public EntityCollection<tarimas_entradas> tarimas_entradas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_entradas>("ClientextModel.fk_usuario", "tarimas_entradas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_entradas>("ClientextModel.fk_usuario", "tarimas_entradas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientextModel", "fk_usuario_s", "tarimas_salidas")]
        public EntityCollection<tarimas_salidas> tarimas_salidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tarimas_salidas>("ClientextModel.fk_usuario_s", "tarimas_salidas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tarimas_salidas>("ClientextModel.fk_usuario_s", "tarimas_salidas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientextModel", Name="vw_inventario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_inventario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vw_inventario.
        /// </summary>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="articulo">Valor inicial de la propiedad articulo.</param>
        /// <param name="num_cajas">Valor inicial de la propiedad num_cajas.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        public static vw_inventario Createvw_inventario(global::System.Int64 id_cliente, global::System.String codigo, global::System.String articulo, global::System.Int64 num_cajas, global::System.Decimal peso, global::System.String tipo)
        {
            vw_inventario vw_inventario = new vw_inventario();
            vw_inventario.id_cliente = id_cliente;
            vw_inventario.codigo = codigo;
            vw_inventario.articulo = articulo;
            vw_inventario.num_cajas = num_cajas;
            vw_inventario.peso = peso;
            vw_inventario.tipo = tipo;
            return vw_inventario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Int64 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int64 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String articulo
        {
            get
            {
                return _articulo;
            }
            set
            {
                if (_articulo != value)
                {
                    OnarticuloChanging(value);
                    ReportPropertyChanging("articulo");
                    _articulo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("articulo");
                    OnarticuloChanged();
                }
            }
        }
        private global::System.String _articulo;
        partial void OnarticuloChanging(global::System.String value);
        partial void OnarticuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 num_cajas
        {
            get
            {
                return _num_cajas;
            }
            set
            {
                if (_num_cajas != value)
                {
                    Onnum_cajasChanging(value);
                    ReportPropertyChanging("num_cajas");
                    _num_cajas = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("num_cajas");
                    Onnum_cajasChanged();
                }
            }
        }
        private global::System.Int64 _num_cajas;
        partial void Onnum_cajasChanging(global::System.Int64 value);
        partial void Onnum_cajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal peso
        {
            get
            {
                return _peso;
            }
            set
            {
                if (_peso != value)
                {
                    OnpesoChanging(value);
                    ReportPropertyChanging("peso");
                    _peso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("peso");
                    OnpesoChanged();
                }
            }
        }
        private global::System.Decimal _peso;
        partial void OnpesoChanging(global::System.Decimal value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                if (_tipo != value)
                {
                    OntipoChanging(value);
                    ReportPropertyChanging("tipo");
                    _tipo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("tipo");
                    OntipoChanged();
                }
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tarima_cliente
        {
            get
            {
                return _tarima_cliente;
            }
            set
            {
                Ontarima_clienteChanging(value);
                ReportPropertyChanging("tarima_cliente");
                _tarima_cliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tarima_cliente");
                Ontarima_clienteChanged();
            }
        }
        private global::System.String _tarima_cliente;
        partial void Ontarima_clienteChanging(global::System.String value);
        partial void Ontarima_clienteChanged();

        #endregion

    
    }

    #endregion

    
}
